name: "Required check"

on:
  pull_request:

jobs:
  required-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check a thing
        run: echo "Required thing checked"
        